#! /bin/bash

# set to 1 for fullscreen
# FULLSCREEN=1
FULLSCREEN=0

# window resolution
# WINX=1680
# WINY=1050
WINX=800
WINY=600

# select alternate graphics
# GFX="oldschool"
GFX="default"

# select alternate sound
SFX="default"

cd "$(dirname $0)"

WHERE="."
RUBYGEMS="-rubygems"

ruby $RUBYGEMS "$WHERE/lib/tools/launcher.rb" squeeze -f $FULLSCREEN -x $WINX -y $WINY -g $GFX -s $SFX $@
